---
# tasks file for PeterMosmans.dokuwiki

# Variable setup.
- name: Include Generic variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Apply permissions for configuration files
  file:
    path: "{{ item }}"
    # state: directory
    mode: "0770"
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    recurse: yes
  with_items:
    - "{{ dokuwiki_base }}/conf"
    - "{{ dokuwiki_savedir }}"
  when: ansible_os_family == 'Debian'
  tags:
    - permission

- name: Download and install latest version of plugins via Dokuwiki's gittool
  become: yes
  shell: "/usr/bin/php {{ dokuwiki_base }}/bin/gittool.php install {{item}}"
  with_items: "{{ dokuwiki_plugins|default([]) }}"
  tags:
    - plugins
    - upgrade

- name: Download and install latest version of templates via Dokuwiki's gittool
  become: yes
  shell: "/usr/bin/php {{ dokuwiki_base }}/bin/gittool.php install template:{{item}}"
  with_items: "{{ dokuwiki_templates|default([]) }}"
  tags:
    - templates
    - upgrade

- block:
  - name: Apply and deploy configuration templates
    template:
      src: "{{ item.src }}"
      dest: "{{ dokuwiki_base }}/conf/{{ item.dest }}"
      mode: "0770"
      group: "{{ dokuwiki_group }}"
      owner: "{{ dokuwiki_user }}"
    with_items:
      - src: acl.auth.php.j2
        dest: acl.auth.php
      - src: local.protected.php.j2
        dest: local.protected.php
      - src: plugins.local.php.j2
        dest: plugins.local.php
      - src: users.auth.php.j2
        dest: users.auth.php
    tags:
      - provision

  - name: Install cron job
    template:
      src: cleanup.sh.j2
      dest: "/etc/cron.daily/cleanup-{{ dokuwiki_name }}"
      mode: "0755"
      group: root
      owner: root
    when: ansible_os_family == 'Debian'
    tags:
      - provision

  - name: Secure configuration
    file:
      path: "{{ dokuwiki_base }}/install.php"
      state: absent
    tags:
      - provision
  when: dokuwiki_provision

- name: Customize template using online files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ dokuwiki_base }}/{{ item.dest }}"
    remote_src: true
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    mode: "{{ item.mode }}"
  with_items: "{{ dokuwiki_overrides|default([]) }}"

- name: Set Dokuwiki page permissions
  file:
    path: "{{ dokuwiki_savedir }}/{{ item }}"
    # state: directory
    mode: "0770"
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    recurse: yes
  with_items:
    - attic
    - cache
    - index
    - locks
    - media
    - media_attic
    - media_meta
    - meta
    - pages
    - tmp
  tags:
    - permission
    - upgrade

- name: Set Dokuwiki configuration permissions
  file:
    path: "{{ dokuwiki_base }}/{{ item }}"
    # state: directory
    mode: "0770"
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    recurse: yes
  with_items:
    - lib/plugins/
    - lib/tpl
  when: ansible_os_family == 'Debian'
  tags:
    - permission
    - upgrade

- name: Apply and deploy Nginx configuration for Dokuwiki
  block:
  - name: Ensure Nginx conf.d exists
    file:
      path: "{{ dokuwiki_webserver_nginx_conf }}/conf.d"
      state: directory
      group: root
      owner: root
      mode: "0770"

  - name: Create dokuwiki config file and restart Nginx
    template:
      src: nginx.dokuwiki.conf.j2
      dest: "/etc/nginx/conf.d/{{ dokuwiki_name }}.conf"
      owner: root
      group: root
      mode: "0640"
    tags:
      - templates
    notify:
      - restart nginx
  when: dokuwiki_webserver is defined and dokuwiki_webserver == "nginx"
  #when: dokuwiki_webserver == "nginx"

- block:
  - name: Apply and deploy Apache configuration for Dokuwiki
    template:
      src: apache.dokuwiki.conf.j2
      dest: "/etc/apache2/sites-available/{{ dokuwiki_name }}.conf"
      owner: root
      group: root
      mode: "0640"
    tags:
      - templates
    notify:
      - restart apache2

  - name: Enable dokuwiki and restart Apache
    command:
      a2ensite {{ dokuwiki_name }}.conf
    notify:
      - restart apache2

  when: dokuwiki_webserver is defined and dokuwiki_webserver == "apache"


 